logins:
    {USERNAME}: {PASSWORD}
options:
    startup-delay: 2000
    port: 20059
    ip-whitelist: []
    log-to-console: true
    log-to-file: 'jsonapi.log'
    salt: '{SALT}'
    anyone-can-use-calladmin: true
    server-name: '{SERVERNAME}'
